server:
  port: 8081

spring:
  application:
    name: AuthorService
  profiles:
    active: default
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888